### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by JosefJ**
just bunch of typos in naming

### CODE REVIEW

**Review by ligi — COMMENTED** [review]
AFAIK Berlin was right ;-)
Or did we make a rename to Belrin that I am not aware of?

**Comment by JosefJ** [comment]
This was a MP & Lili joke ;)

**Comment by ligi** [comment]
ah dam - missed the notification on this one - sorry - is this still relevant?

**Comment by soc1c** [comment]
(:

**Pull request closed without merging**
